// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	structpb "google.golang.org/protobuf/types/known/structpb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NodeState int32

const (
	NodeState_down NodeState = 0
	NodeState_up   NodeState = 1
)

var NodeState_name = map[int32]string{
	0: "down",
	1: "up",
}

var NodeState_value = map[string]int32{
	"down": 0,
	"up":   1,
}

func (x NodeState) String() string {
	return proto.EnumName(NodeState_name, int32(x))
}

func (NodeState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{0}
}

type AgentState int32

const (
	AgentState_healthy   AgentState = 0
	AgentState_unhealthy AgentState = 1
)

var AgentState_name = map[int32]string{
	0: "healthy",
	1: "unhealthy",
}

var AgentState_value = map[string]int32{
	"healthy":   0,
	"unhealthy": 1,
}

func (x AgentState) String() string {
	return proto.EnumName(AgentState_name, int32(x))
}

func (AgentState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1}
}

type MessageType int32

const (
	MessageType_metric MessageType = 0
	MessageType_event  MessageType = 1
)

var MessageType_name = map[int32]string{
	0: "metric",
	1: "event",
}

var MessageType_value = map[string]int32{
	"metric": 0,
	"event":  1,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{2}
}

type Message struct {
	Timestamp            int64       `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type                 MessageType `protobuf:"varint,2,opt,name=type,proto3,enum=metrika.MessageType" json:"type,omitempty"`
	NodeState            NodeState   `protobuf:"varint,3,opt,name=nodeState,proto3,enum=metrika.NodeState" json:"nodeState,omitempty"`
	AgentState           AgentState  `protobuf:"varint,4,opt,name=agentState,proto3,enum=metrika.AgentState" json:"agentState,omitempty"`
	Name                 string      `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Body                 []byte      `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Message) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_metric
}

func (m *Message) GetNodeState() NodeState {
	if m != nil {
		return m.NodeState
	}
	return NodeState_down
}

func (m *Message) GetAgentState() AgentState {
	if m != nil {
		return m.AgentState
	}
	return AgentState_healthy
}

func (m *Message) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Message) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Event struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc                 string           `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Values               *structpb.Struct `protobuf:"bytes,3,opt,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Event) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Event) GetValues() *structpb.Struct {
	if m != nil {
		return m.Values
	}
	return nil
}

type PlatformMessage struct {
	Data                 []*Message `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	AgentUUID            string     `protobuf:"bytes,2,opt,name=agentUUID,proto3" json:"agentUUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PlatformMessage) Reset()         { *m = PlatformMessage{} }
func (m *PlatformMessage) String() string { return proto.CompactTextString(m) }
func (*PlatformMessage) ProtoMessage()    {}
func (*PlatformMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{2}
}

func (m *PlatformMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatformMessage.Unmarshal(m, b)
}
func (m *PlatformMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatformMessage.Marshal(b, m, deterministic)
}
func (m *PlatformMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatformMessage.Merge(m, src)
}
func (m *PlatformMessage) XXX_Size() int {
	return xxx_messageInfo_PlatformMessage.Size(m)
}
func (m *PlatformMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatformMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PlatformMessage proto.InternalMessageInfo

func (m *PlatformMessage) GetData() []*Message {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *PlatformMessage) GetAgentUUID() string {
	if m != nil {
		return m.AgentUUID
	}
	return ""
}

type PlatformResponse struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlatformResponse) Reset()         { *m = PlatformResponse{} }
func (m *PlatformResponse) String() string { return proto.CompactTextString(m) }
func (*PlatformResponse) ProtoMessage()    {}
func (*PlatformResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{3}
}

func (m *PlatformResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatformResponse.Unmarshal(m, b)
}
func (m *PlatformResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatformResponse.Marshal(b, m, deterministic)
}
func (m *PlatformResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatformResponse.Merge(m, src)
}
func (m *PlatformResponse) XXX_Size() int {
	return xxx_messageInfo_PlatformResponse.Size(m)
}
func (m *PlatformResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatformResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlatformResponse proto.InternalMessageInfo

func (m *PlatformResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterEnum("metrika.NodeState", NodeState_name, NodeState_value)
	proto.RegisterEnum("metrika.AgentState", AgentState_name, AgentState_value)
	proto.RegisterEnum("metrika.MessageType", MessageType_name, MessageType_value)
	proto.RegisterType((*Message)(nil), "metrika.Message")
	proto.RegisterType((*Event)(nil), "metrika.Event")
	proto.RegisterType((*PlatformMessage)(nil), "metrika.PlatformMessage")
	proto.RegisterType((*PlatformResponse)(nil), "metrika.PlatformResponse")
}

func init() {
	proto.RegisterFile("agent.proto", fileDescriptor_56ede974c0020f77)
}

var fileDescriptor_56ede974c0020f77 = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x4f, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0xb3, 0x8d, 0xe3, 0xd4, 0x63, 0xfe, 0x58, 0x03, 0x12, 0xa6, 0x2a, 0x92, 0x15, 0xf5,
	0x60, 0xe5, 0xe0, 0x54, 0xe9, 0x91, 0x03, 0x02, 0x81, 0x04, 0x07, 0x10, 0xda, 0x36, 0x17, 0x4e,
	0x6c, 0xe2, 0x69, 0x1a, 0x61, 0xef, 0x5a, 0xde, 0x75, 0x51, 0xbe, 0x2d, 0x1f, 0x05, 0x65, 0xea,
	0x3f, 0xa5, 0x1c, 0x7a, 0x9b, 0x9d, 0x79, 0x6f, 0x35, 0xef, 0x37, 0x10, 0xaa, 0x2d, 0x69, 0x97,
	0x55, 0xb5, 0x71, 0x06, 0xa7, 0x25, 0xb9, 0x7a, 0xf7, 0x4b, 0x9d, 0x9c, 0x6e, 0x8d, 0xd9, 0x16,
	0xb4, 0xe0, 0xf6, 0xba, 0xb9, 0x5e, 0x58, 0x57, 0x37, 0x9b, 0x56, 0x36, 0xfb, 0x23, 0x60, 0xfa,
	0x95, 0xac, 0x55, 0x5b, 0xc2, 0x53, 0x08, 0xdc, 0xae, 0x24, 0xeb, 0x54, 0x59, 0xc5, 0x22, 0x11,
	0xe9, 0x58, 0x0e, 0x0d, 0x4c, 0xc1, 0x73, 0xfb, 0x8a, 0xe2, 0xa3, 0x44, 0xa4, 0xcf, 0x96, 0x2f,
	0xb3, 0xf6, 0xff, 0xac, 0x75, 0x5f, 0xed, 0x2b, 0x92, 0xac, 0xc0, 0x73, 0x08, 0xb4, 0xc9, 0xe9,
	0xd2, 0x29, 0x47, 0xf1, 0x98, 0xe5, 0xd8, 0xcb, 0xbf, 0x75, 0x13, 0x39, 0x88, 0xf0, 0x02, 0x80,
	0x77, 0xbf, 0xb3, 0x78, 0x6c, 0x79, 0xd1, 0x5b, 0xde, 0xf7, 0x23, 0x79, 0x4f, 0x86, 0x08, 0x9e,
	0x56, 0x25, 0xc5, 0x93, 0x44, 0xa4, 0x81, 0xe4, 0xfa, 0xd0, 0x5b, 0x9b, 0x7c, 0x1f, 0xfb, 0x89,
	0x48, 0x9f, 0x48, 0xae, 0x67, 0x3f, 0x61, 0xf2, 0xe9, 0x96, 0xb4, 0xeb, 0x0d, 0xe2, 0x5f, 0x43,
	0x4e, 0x76, 0xc3, 0xa9, 0x02, 0xc9, 0x35, 0x2e, 0xc0, 0xbf, 0x55, 0x45, 0x43, 0x96, 0x97, 0x0f,
	0x97, 0xaf, 0xb2, 0x3b, 0x84, 0x59, 0x87, 0x30, 0xbb, 0x64, 0x84, 0xb2, 0x95, 0xcd, 0x56, 0xf0,
	0xfc, 0x7b, 0xa1, 0xdc, 0xb5, 0xa9, 0xcb, 0x8e, 0xe5, 0x19, 0x78, 0xb9, 0x72, 0x2a, 0x16, 0xc9,
	0x38, 0x0d, 0x97, 0xd1, 0x43, 0x5a, 0x92, 0xa7, 0x07, 0xe2, 0x1c, 0x68, 0xb5, 0xfa, 0xf2, 0xb1,
	0x5d, 0x61, 0x68, 0xcc, 0xce, 0x21, 0xea, 0xbe, 0x95, 0x64, 0x2b, 0xa3, 0xed, 0x23, 0x37, 0x9a,
	0xbf, 0x81, 0xa0, 0xe7, 0x8b, 0xc7, 0xe0, 0xe5, 0xe6, 0xb7, 0x8e, 0x46, 0xe8, 0xc3, 0x51, 0x53,
	0x45, 0x62, 0x9e, 0x02, 0x0c, 0x2c, 0x31, 0x84, 0xe9, 0x0d, 0xa9, 0xc2, 0xdd, 0xec, 0xa3, 0x11,
	0x3e, 0x85, 0xa0, 0xd1, 0xdd, 0x53, 0xcc, 0xcf, 0x20, 0xbc, 0x77, 0x57, 0x04, 0xf0, 0x39, 0xc0,
	0x26, 0x1a, 0x61, 0x00, 0x13, 0x3a, 0xe0, 0x8c, 0xc4, 0xf2, 0x33, 0x4c, 0x78, 0x5b, 0x7c, 0x07,
	0xc7, 0x57, 0xb5, 0xd2, 0xb6, 0xdc, 0x39, 0x8c, 0xfb, 0xac, 0x0f, 0x98, 0x9c, 0xbc, 0xfe, 0x6f,
	0xd2, 0xc5, 0xfa, 0x10, 0xfc, 0x98, 0x66, 0x6f, 0x4b, 0x93, 0x53, 0xb1, 0xf6, 0x99, 0xf2, 0xc5,
	0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfa, 0xd7, 0x3f, 0xd5, 0xce, 0x02, 0x00, 0x00,
}
