//go:build algorand

// Code generated by protobind -blockchain algorand; DO NOT EDIT.

package discover

// Use the following code to bootstrap a new node_example.go file:
// ```go
// //go:build example
// 
// package discover
// 
// //go:generate protobind -blockchain example ./...
// ```

//go:generate protobind -blockchain algorand ./...

import (
	blockchain "agent/algorand"

	"go.uber.org/zap"
)

func Init() {
	var err error
	log := zap.S()

	configPath = blockchain.DefaultAlgorandPath

	chain, err = blockchain.NewAlgorand()
	if err != nil {
		log.Fatalw("failed to load protocol configuration file", zap.Error(err))
	}
}
