//go:build solana

// Code generated by protobind -blockchain solana; DO NOT EDIT.

package discover

// Use the following code to bootstrap a new node_example.go file:
// ```go
// //go:build example
//
// package discover
//
// //go:generate protobind -blockchain example ./...
// ```

//go:generate protobind -blockchain solana ./...

import (
	blockchain "agent/solana"

	"go.uber.org/zap"
)

var (
	// DefaultDiscoveryHintsSystemd default glob pattern to detect Solana nodes run by systemd
	DefaultDiscoveryHintsSystemd = []string{}

	// DefaultDiscoveryHintsDocker default regular expression to detect Solana nodes run by docker
	DefaultDiscoveryHintsDocker = []string{}

	falseBool = false
)

func Init() {
	var err error
	log := zap.S()

	configPath = blockchain.DefaultSolanaPath

	chain, err = blockchain.NewSolana()
	if err != nil {
		log.Fatalw("failed to load protocol configuration file", zap.Error(err))
	}
}
