//go:build flow

// Code generated by protobind -blockchain flow; DO NOT EDIT.

package discover

// Use the following code to bootstrap a new node_example.go file:
// ```go
// //go:build example
// 
// package discover
// 
// //go:generate protobind -blockchain example ./...
// ```

//go:generate protobind -blockchain flow ./...

import (
	blockchain "agent/flow"

	"go.uber.org/zap"
)

func Init() {
	var err error
	log := zap.S()

	configPath = blockchain.DefaultFlowPath

	chain, err = blockchain.NewFlow()
	if err != nil {
		log.Fatalw("failed to load protocol configuration file", zap.Error(err))
	}
}
