---
platform:

  # batch_n: integer, the maximum number of metrics/events to be emitted at
  # each publish operation to the platform.
  batch_n: 1000

  # max_publish_interval: duration, the maximum interval to wait between two
  # consecutive publish operations to the platform.
  max_publish_interval: 5s
  
  # transport_timeout: duration, configures the timeout for publish
  # operations to the platform.
  transport_timeout: 10s

  # addr: string, network address of the platform for publishing
  addr: 0.0.0.0:9600

  # uri: string, platform publishing endpoint
  uri: /

buffer:

  # size: integer, the maximum memory the agent is allowed to preserve in bytes.
  size: 52428800

  # ttl: duration, a Time-To-Live for any buffered data. Data will never expire
  # for zero TTL values.
  ttl: 0s

runtime:

  logging:

    # outputs: list of outputs for runtime logs.
    #
    # Possible values are one of the standard I/O streams # (i.e stdout, stderr)
    # or a full/relative path to a filename (i.e logs/agent.log).
    outputs:
      - stdout

    # level: logging level for runtime logs.
    #
    # Possible values are: info, warning (recommended), debug, error.
    level: debug

  # metrics_addr: string, network address to get Prometheus metrics about the
  # agent's runtime.
  metrics_addr: :9000

  # sampling_interval: duration, default interval used by Watchers that use
  # polling for collecting metrics/events.
  sampling_interval: 5s

  # read_stream: boolean, enables stream reading by implementations under
  # pkg/contrib. Default value is false.
  read_stream: false

  # watchers: list[object], list of watchers to be enabled on agent startup.
  # The watcher constructor name must be registered first in the pkg/collector.
  watchers:
    - type: prometheus.proc.cpu
    - type: prometheus.proc.net.netstat_linux
    - type: prometheus.proc.net.arp_linux
    - type: prometheus.proc.stat_linux
    - type: prometheus.proc.conntrack_linux
    - type: prometheus.proc.diskstats
    - type: prometheus.proc.entropy
    - type: prometheus.proc.filefd
    - type: prometheus.proc.filesystem
    - type: prometheus.proc.loadavg
    - type: prometheus.proc.meminfo
    - type: prometheus.proc.netclass
    - type: prometheus.proc.netdev
    - type: prometheus.proc.sockstat
    - type: prometheus.proc.textfile
    - type: prometheus.time
    - type: prometheus.uname
    - type: prometheus.vmstat
